spring:
  datasource:
    username: sa
    hikari:
      jdbc-url: jdbc:h2:~/subway;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true